mv '$scope=angular.element(".window").scope().html' '2014-05-08-$scope=angular.element(".window").scope().html'
mv '$scope=angular.element(".window").scope().resources' '2014-05-08-$scope=angular.element(".window").scope()'
mv '13.3 文件的打开与关闭.html' '2011-03-12-13.3 文件的打开与关闭.html'
mv '13.3 文件的打开与关闭.resources' '2011-03-12-13.3 文件的打开与关闭'
mv '20171012.html' '2017-10-12-20171012.html'
mv '20171012.resources' '2017-10-12-20171012'
mv 'A basic understanding of the characteristics of atomic operation.html' '2014-09-14-A basic understanding of the characteristics of atomic operation.html'
mv 'A basic understanding of the characteristics of atomic operation.resources' '2014-09-14-A basic understanding of the characteristics of atomic operation'
mv 'A good commit.html' '2016-11-05-A good commit.html'
mv 'A good commit.resources' '2016-11-05-A good commit'
mv 'A managed object model is a schema that provides a description of the managed objects.html' '2014-02-26-A managed object model is a schema that provides a description of the managed objects.html'
mv 'A managed object model is a schema that provides a description of the managed objects.resources' '2014-02-26-A managed object model is a schema that provides a description of the managed objects'
mv 'Active Record Callbacks — Ruby on Rails Guides.html' '2014-06-26-Active Record Callbacks — Ruby on Rails Guides.html'
mv 'Active Record Callbacks — Ruby on Rails Guides.resources' '2014-06-26-Active Record Callbacks — Ruby on Rails Guides'
mv 'AngularJS: API: $q.html' '2014-11-20-AngularJS: API: $q.html'
mv 'AngularJS: API: $q.resources' '2014-11-20-AngularJS: API: $q'
mv 'Application Protocols.html' '2014-07-16-Application Protocols.html'
mv 'Application Protocols.resources' '2014-07-16-Application Protocols'
mv 'application UI structure and style.html' '2013-04-26-application UI structure and style.html'
mv 'application UI structure and style.resources' '2013-04-26-application UI structure and style'
mv 'arsduo/koala.html' '2015-05-28-arsduo/koala.html'
mv 'arsduo/koala.resources' '2015-05-28-arsduo/koala'
mv 'asynchronous workflow is conceptually the same as synchronous workflow.html' '2013-09-05-asynchronous workflow is conceptually the same as synchronous workflow.html'
mv 'asynchronous workflow is conceptually the same as synchronous workflow.resources' '2013-09-05-asynchronous workflow is conceptually the same as synchronous workflow'
mv 'Asynchronous XMLHttpRequest implementation.html' '2014-02-19-Asynchronous XMLHttpRequest implementation.html'
mv 'Asynchronous XMLHttpRequest implementation.resources' '2014-02-19-Asynchronous XMLHttpRequest implementation'
mv 'Backend requirements.html' '2014-09-14-Backend requirements.html'
mv 'Backend requirements.resources' '2014-09-14-Backend requirements'
mv 'Bash expansion.html' '2012-07-17-Bash expansion.html'
mv 'Bash expansion.resources' '2012-07-17-Bash expansion'
mv 'C++ Template.html' '2012-11-07-C++ Template.html'
mv 'C++ Template.resources' '2012-11-07-C++ Template'
mv 'C++知识地图.html' '2011-12-13-C++知识地图.html'
mv 'C++知识地图.resources' '2011-12-13-C++知识地图'
mv 'Capybara 测试代码（跑在Ruby process），起了Rails服务器代码（跑在capybara同一个Ruby process的另一个thread），连接着poltergeist driver代码（跟Capybara测试代码运行在同一个thread）；.html' '2016-11-05-Capybara 测试代码（跑在Ruby process），起了Rails服务器代码（跑在capybara同一个Ruby process的另一个thread），连接着poltergeist driver代码（跟Capybara测试代码运行在同一个thread）；.html'
mv 'Capybara 测试代码（跑在Ruby process），起了Rails服务器代码（跑在capybara同一个Ruby process的另一个thread），连接着poltergeist driver代码（跟Capybara测试代码运行在同一个thread）；.resources' '2016-11-05-Capybara 测试代码（跑在Ruby process），起了Rails服务器代码（跑在capybara同一个Ruby process的另一个thread），连接着poltergeist driver代码（跟Capybara测试代码运行在同一个thread）；'
mv 'clean unstaged files in Git.html' '2015-08-03-clean unstaged files in Git.html'
mv 'clean unstaged files in Git.resources' '2015-08-03-clean unstaged files in Git'
mv 'Client is graphic heavy, UI centric..html' '2016-11-05-Client is graphic heavy, UI centric..html'
mv 'Client is graphic heavy, UI centric..resources' '2016-11-05-Client is graphic heavy, UI centric.'
mv 'Creating high quality code.html' '2013-09-09-Creating high quality code.html'
mv 'Creating high quality code.resources' '2013-09-09-Creating high quality code'
mv 'CRUD on Managed Objects.html' '2014-02-27-CRUD on Managed Objects.html'
mv 'CRUD on Managed Objects.resources' '2014-02-27-CRUD on Managed Objects'
mv 'csrf-token.html' '2014-12-18-csrf-token.html'
mv 'csrf-token.resources' '2014-12-18-csrf-token'
mv 'CSS 布局.html' '2014-08-08-CSS 布局.html'
mv 'CSS 布局.resources' '2014-08-08-CSS 布局'
mv 'Custom HTML attribute requires a custom helper.html' '2013-06-19-Custom HTML attribute requires a custom helper.html'
mv 'Custom HTML attribute requires a custom helper.resources' '2013-06-19-Custom HTML attribute requires a custom helper'
mv 'C语言指针、数组学习笔记.html' '2010-11-19-C语言指针、数组学习笔记.html'
mv 'C语言指针、数组学习笔记.resources' '2010-11-19-C语言指针、数组学习笔记'
mv 'Data conflict resolution 数据冲突的解决.html' '2014-08-11-Data conflict resolution 数据冲突的解决.html'
mv 'Data conflict resolution 数据冲突的解决.resources' '2014-08-11-Data conflict resolution 数据冲突的解决'
mv 'Data object management.html' '2013-10-31-Data object management.html'
mv 'Data object management.resources' '2013-10-31-Data object management'
mv 'Defining Abilities with Blocks · ryanb/cancan Wiki.html' '2014-08-28-Defining Abilities with Blocks · ryanb/cancan Wiki.html'
mv 'Defining Abilities with Blocks · ryanb/cancan Wiki.resources' '2014-08-28-Defining Abilities with Blocks · ryanb/cancan Wiki'
mv 'Democracy is not a silver bullet.html' '2015-12-20-Democracy is not a silver bullet.html'
mv 'Democracy is not a silver bullet.resources' '2015-12-20-Democracy is not a silver bullet'
mv 'Develop.html' '2016-11-05-Develop.html'
mv 'Develop.resources' '2016-11-05-Develop'
mv 'differece between controller action "new" and "create".html' '2013-05-03-differece between controller action "new" and "create".html'
mv 'differece between controller action "new" and "create".resources' '2013-05-03-differece between controller action "new" and "create"'
mv 'Difference between navigation bar transition and collection view transition:.html' '2013-09-26-Difference between navigation bar transition and collection view transition:.html'
mv 'Difference between navigation bar transition and collection view transition:.resources' '2013-09-26-Difference between navigation bar transition and collection view transition:'
mv 'Diving into CanJS: Part 2 | Nettuts+.html' '2013-07-08-Diving into CanJS: Part 2 | Nettuts+.html'
mv 'Diving into CanJS: Part 2 | Nettuts+.resources' '2013-07-08-Diving into CanJS: Part 2 | Nettuts+'
mv 'elasticsearch deb Ubuntu install path.html' '2014-05-20-elasticsearch deb Ubuntu install path.html'
mv 'elasticsearch deb Ubuntu install path.resources' '2014-05-20-elasticsearch deb Ubuntu install path'
mv 'eldk directory analysis.html' '2012-12-31-eldk directory analysis.html'
mv 'eldk directory analysis.resources' '2012-12-31-eldk directory analysis'
mv 'Ember.js - Understanding Ember.js: Managing Asynchrony.html' '2015-05-20-Ember.js - Understanding Ember.js: Managing Asynchrony.html'
mv 'Ember.js - Understanding Ember.js: Managing Asynchrony.resources' '2015-05-20-Ember.js - Understanding Ember.js: Managing Asynchrony'
mv 'Event handling in Javascript( and in general ).html' '2012-08-17-Event handling in Javascript( and in general ).html'
mv 'Event handling in Javascript( and in general ).resources' '2012-08-17-Event handling in Javascript( and in general )'
mv 'evernote merge order.html' '2013-01-01-evernote merge order.html'
mv 'evernote merge order.resources' '2013-01-01-evernote merge order'
mv 'file uploads.html' '2014-09-24-file uploads.html'
mv 'file uploads.resources' '2014-09-24-file uploads'
mv 'form processing.html' '2013-04-27-form processing.html'
mv 'form processing.resources' '2013-04-27-form processing'
mv 'How ember-data implements relationships between models.html' '2015-06-12-How ember-data implements relationships between models.html'
mv 'How ember-data implements relationships between models.resources' '2015-06-12-How ember-data implements relationships between models'
mv 'How important is business for a company?.html' '2016-07-12-How important is business for a company?.html'
mv 'How important is business for a company?.resources' '2016-07-12-How important is business for a company?'
mv 'How PhoneGap works.html' '2013-11-13-How PhoneGap works.html'
mv 'How PhoneGap works.resources' '2013-11-13-How PhoneGap works'
mv 'How RubyGems installs  a gem.html' '2013-10-10-How RubyGems installs  a gem.html'
mv 'How RubyGems installs  a gem.resources' '2013-10-10-How RubyGems installs  a gem'
mv 'How to add Github repo as Xcode git remote origin.html' '2014-02-21-How to add Github repo as Xcode git remote origin.html'
mv 'How to add Github repo as Xcode git remote origin.resources' '2014-02-21-How to add Github repo as Xcode git remote origin'
mv 'How to build new habits.html' '2017-07-30-How to build new habits.html'
mv 'How to build new habits.resources' '2017-07-30-How to build new habits'
mv 'how to define public and private method and property, also where to define instance variable..html' '2013-08-30-how to define public and private method and property, also where to define instance variable..html'
mv 'how to define public and private method and property, also where to define instance variable..resources' '2013-08-30-how to define public and private method and property, also where to define instance variable.'
mv 'how to examine if a model record is valid in Rails.html' '2013-10-14-how to examine if a model record is valid in Rails.html'
mv 'how to examine if a model record is valid in Rails.resources' '2013-10-14-how to examine if a model record is valid in Rails'
mv 'How to handle errors.html' '2013-09-26-How to handle errors.html'
mv 'How to handle errors.resources' '2013-09-26-How to handle errors'
mv 'How to make sure your code works as expected?.html' '2013-09-13-How to make sure your code works as expected?.html'
mv 'How to make sure your code works as expected?.resources' '2013-09-13-How to make sure your code works as expected?'
mv 'How to request a ScrumWork account.html' '2015-04-08-How to request a ScrumWork account.html'
mv 'How to request a ScrumWork account.resources' '2015-04-08-How to request a ScrumWork account'
mv 'I/O redirection.html' '2012-07-17-I/O redirection.html'
mv 'I/O redirection.resources' '2012-07-17-I/O redirection'
mv 'In Ember, it’s route which provides data.html' '2015-07-03-In Ember, it’s route which provides data.html'
mv 'In Ember, it’s route which provides data.resources' '2015-07-03-In Ember, it’s route which provides data'
mv 'inspirations.html' '2014-05-17-inspirations.html'
mv 'inspirations.resources' '2014-05-17-inspirations'
mv 'invoice view bug.html' '2014-01-02-invoice view bug.html'
mv 'invoice view bug.resources' '2014-01-02-invoice view bug'
mv 'iOS build bug.html' '2014-01-02-iOS build bug.html'
mv 'iOS build bug.resources' '2014-01-02-iOS build bug'
mv 'Is talking to services over network that slow?.html' '2015-11-05-Is talking to services over network that slow?.html'
mv 'Is talking to services over network that slow?.resources' '2015-11-05-Is talking to services over network that slow?'
mv 'Issues encountered dockerizing my api app.html' '2015-11-10-Issues encountered dockerizing my api app.html'
mv 'Issues encountered dockerizing my api app.resources' '2015-11-10-Issues encountered dockerizing my api app'
mv 'javascript prototype-based Inheritance.html' '2014-06-15-javascript prototype-based Inheritance.html'
mv 'javascript prototype-based Inheritance.resources' '2014-06-15-javascript prototype-based Inheritance'
mv 'Js function as object constructors.html' '2014-06-15-Js function as object constructors.html'
mv 'Js function as object constructors.resources' '2014-06-15-Js function as object constructors'
mv 'JS prototype-based OO key steps.html' '2017-07-13-JS prototype-based OO key steps.html'
mv 'JS prototype-based OO key steps.resources' '2017-07-13-JS prototype-based OO key steps'
mv 'Linux Kernel.html' '2016-11-05-Linux Kernel.html'
mv 'Linux Kernel.resources' '2016-11-05-Linux Kernel'
mv 'Linux system cross-compiling dependencies.html' '2013-11-29-Linux system cross-compiling dependencies.html'
mv 'Linux system cross-compiling dependencies.resources' '2013-11-29-Linux system cross-compiling dependencies'
mv 'manually trigger page style refresh.html' '2013-07-04-manually trigger page style refresh.html'
mv 'manually trigger page style refresh.resources' '2013-07-04-manually trigger page style refresh'
mv 'migration and model.html' '2013-04-28-migration and model.html'
mv 'migration and model.resources' '2013-04-28-migration and model'
mv 'Mistake I made when analyzing requirements.html' '2016-04-13-Mistake I made when analyzing requirements.html'
mv 'Mistake I made when analyzing requirements.resources' '2016-04-13-Mistake I made when analyzing requirements'
mv 'Model, View, Controller analog in Backbone.js.html' '2013-11-14-Model, View, Controller analog in Backbone.js.html'
mv 'Model, View, Controller analog in Backbone.js.resources' '2013-11-14-Model, View, Controller analog in Backbone.js'
mv 'Motivation. Goal. And plan.html' '2017-06-21-Motivation. Goal. And plan.html'
mv 'Motivation. Goal. And plan.resources' '2017-06-21-Motivation. Goal. And plan'
mv 'Multi-language progarmming.html' '2013-03-02-Multi-language progarmming.html'
mv 'Multi-language progarmming.resources' '2013-03-02-Multi-language progarmming'
mv 'multitasking in iOS 7.html' '2013-09-26-multitasking in iOS 7.html'
mv 'multitasking in iOS 7.resources' '2013-09-26-multitasking in iOS 7'
mv 'MVC.html' '2013-04-27-MVC.html'
mv 'MVC.resources' '2013-04-27-MVC'
mv 'N=?NP.html' '2011-12-13-N=?NP.html'
mv 'N=?NP.resources' '2011-12-13-N=?NP'
mv 'named routes.html' '2013-04-26-named routes.html'
mv 'named routes.resources' '2013-04-26-named routes'
mv 'Networking is an essential part of computer programs, just like GUI. 所以服务端软件并不因使.html' '2014-07-11-Networking is an essential part of computer programs, just like GUI. 所以服务端软件并不因使.html'
mv 'Networking is an essential part of computer programs, just like GUI. 所以服务端软件并不因使.resources' '2014-07-11-Networking is an essential part of computer programs, just like GUI. 所以服务端软件并不因使'
mv 'Ng service vs factory.html' '2014-12-08-Ng service vs factory.html'
mv 'Ng service vs factory.resources' '2014-12-08-Ng service vs factory'
mv 'note on ruby: "?" question mark, return value, "@" instance variable.html' '2013-04-11-note on ruby: "?" question mark, return value, "@" instance variable.html'
mv 'note on ruby: "?" question mark, return value, "@" instance variable.resources' '2013-04-11-note on ruby: "?" question mark, return value, "@" instance variable'
mv 'note on ruby: parentheses on function calls are optional..html' '2013-04-11-note on ruby: parentheses on function calls are optional..html'
mv 'note on ruby: parentheses on function calls are optional..resources' '2013-04-11-note on ruby: parentheses on function calls are optional.'
mv 'OAuth usage examples.html' '2015-05-04-OAuth usage examples.html'
mv 'OAuth usage examples.resources' '2015-05-04-OAuth usage examples'
mv 'On 单片机.html' '2012-02-11-On 单片机.html'
mv 'On 单片机.resources' '2012-02-11-On 单片机'
mv 'PhoneGap project directory analysis.html' '2013-11-15-PhoneGap project directory analysis.html'
mv 'PhoneGap project directory analysis.resources' '2013-11-15-PhoneGap project directory analysis'
mv 'php.internals: Re: Flexible function naming.html' '2016-12-28-php.internals: Re: Flexible function naming.html'
mv 'php.internals: Re: Flexible function naming.resources' '2016-12-28-php.internals: Re: Flexible function naming'
mv 'Problems MVC solve.html' '2015-12-23-Problems MVC solve.html'
mv 'Problems MVC solve.resources' '2015-12-23-Problems MVC solve'
mv 'Procedures of debugging.html' '2015-04-25-Procedures of debugging.html'
mv 'Procedures of debugging.resources' '2015-04-25-Procedures of debugging'
mv 'Programming Tools.html' '2012-11-02-Programming Tools.html'
mv 'Programming Tools.resources' '2012-11-02-Programming Tools'
mv 'prototype-based inheritance.html' '2014-06-15-prototype-based inheritance.html'
mv 'prototype-based inheritance.resources' '2014-06-15-prototype-based inheritance'
mv 'Ptxdist configuration method.html' '2013-01-01-Ptxdist configuration method.html'
mv 'Ptxdist configuration method.resources' '2013-01-01-Ptxdist configuration method'
mv 'Public-key cryptography - Wikipedia, the free encyclopedia.html' '2015-04-16-Public-key cryptography - Wikipedia, the free encyclopedia.html'
mv 'Public-key cryptography - Wikipedia, the free encyclopedia.resources' '2015-04-16-Public-key cryptography - Wikipedia, the free encyclopedia'
mv 'rails app setup.html' '2014-07-22-rails app setup.html'
mv 'rails app setup.resources' '2014-07-22-rails app setup'
mv 'rails install note.html' '2013-04-09-rails install note.html'
mv 'rails install note.resources' '2013-04-09-rails install note'
mv 'rails/activerecord at master · rails/rails · GitHub.html' '2015-04-29-rails/activerecord at master · rails/rails · GitHub.html'
mv 'rails/activerecord at master · rails/rails · GitHub.resources' '2015-04-29-rails/activerecord at master · rails/rails · GitHub'
mv 'React crash course notes.html' '2017-11-08-React crash course notes.html'
mv 'React crash course notes.resources' '2017-11-08-React crash course notes'
mv 'reactjs/react-redux.html' '2017-11-09-reactjs/react-redux.html'
mv 'reactjs/react-redux.resources' '2017-11-09-reactjs/react-redux'
mv 'reasons to use objects to represent value instead of scalar variable.html' '2013-09-06-reasons to use objects to represent value instead of scalar variable.html'
mv 'reasons to use objects to represent value instead of scalar variable.resources' '2013-09-06-reasons to use objects to represent value instead of scalar variable'
mv 'Redux FAQs.html' '2016-07-26-Redux FAQs.html'
mv 'Redux FAQs.resources' '2016-07-26-Redux FAQs'
mv 'relationship between RubyGems and Ruby..html' '2013-04-09-relationship between RubyGems and Ruby..html'
mv 'relationship between RubyGems and Ruby..resources' '2013-04-09-relationship between RubyGems and Ruby.'
mv 'Remembering our freedom fighter Aaron Swartz.html' '2016-04-10-Remembering our freedom fighter Aaron Swartz.html'
mv 'Remembering our freedom fighter Aaron Swartz.resources' '2016-04-10-Remembering our freedom fighter Aaron Swartz'
mv 'Roles in Ember.html' '2015-05-18-Roles in Ember.html'
mv 'Roles in Ember.resources' '2015-05-18-Roles in Ember'
mv 'Ruby on Rails Guides: Getting Started with Rails.html' '2013-09-03-Ruby on Rails Guides: Getting Started with Rails.html'
mv 'Ruby on Rails Guides: Getting Started with Rails.resources' '2013-09-03-Ruby on Rails Guides: Getting Started with Rails'
mv 'Ruby: why not interface checking?.html' '2014-05-15-Ruby: why not interface checking?.html'
mv 'Ruby: why not interface checking?.resources' '2014-05-15-Ruby: why not interface checking?'
mv 'Same old goodness:.html' '2016-11-05-Same old goodness:.html'
mv 'Same old goodness:.resources' '2016-11-05-Same old goodness:'
mv 'Scrum terms.html' '2015-04-01-Scrum terms.html'
mv 'Scrum terms.resources' '2015-04-01-Scrum terms'
mv 'Setting up Unicorn with Nginx.html' '2013-09-22-Setting up Unicorn with Nginx.html'
mv 'Setting up Unicorn with Nginx.resources' '2013-09-22-Setting up Unicorn with Nginx'
mv 'Should view layer do computation?.html' '2014-04-16-Should view layer do computation?.html'
mv 'Should view layer do computation?.resources' '2014-04-16-Should view layer do computation?'
mv 'State of app. Relationship between React and Redux.html' '2017-11-09-State of app. Relationship between React and Redux.html'
mv 'State of app. Relationship between React and Redux.resources' '2017-11-09-State of app. Relationship between React and Redux'
mv 'steps for running a custom animated view controller transition.html' '2014-08-10-steps for running a custom animated view controller transition.html'
mv 'steps for running a custom animated view controller transition.resources' '2014-08-10-steps for running a custom animated view controller transition'
mv 'Steps to properly setup VPN speed up tool with intranet.html' '2015-07-22-Steps to properly setup VPN speed up tool with intranet.html'
mv 'Steps to properly setup VPN speed up tool with intranet.resources' '2015-07-22-Steps to properly setup VPN speed up tool with intranet'
mv 'Story point only cover Dev essential complexity..html' '2016-11-05-Story point only cover Dev essential complexity..html'
mv 'Story point only cover Dev essential complexity..resources' '2016-11-05-Story point only cover Dev essential complexity.'
mv 'Style - React Native.html' '2017-11-14-Style - React Native.html'
mv 'Style - React Native.resources' '2017-11-14-Style - React Native'
mv 'text editor features.html' '2014-07-09-text editor features.html'
mv 'text editor features.resources' '2014-07-09-text editor features'
mv 'The crazy time for riding service in China.html' '2016-04-10-The crazy time for riding service in China.html'
mv 'The crazy time for riding service in China.resources' '2016-04-10-The crazy time for riding service in China'
mv 'The difference between Noblocking IO and Asyncronous IO.html' '2014-02-16-The difference between Noblocking IO and Asyncronous IO.html'
mv 'The difference between Noblocking IO and Asyncronous IO.resources' '2014-02-16-The difference between Noblocking IO and Asyncronous IO'
mv 'Things Linus Tarvolds said.html' '2015-12-28-Things Linus Tarvolds said.html'
mv 'Things Linus Tarvolds said.resources' '2015-12-28-Things Linus Tarvolds said'
mv 'Thread synchronization, deadlock avoidance( same locking order).html' '2016-11-05-Thread synchronization, deadlock avoidance( same locking order).html'
mv 'Thread synchronization, deadlock avoidance( same locking order).resources' '2016-11-05-Thread synchronization, deadlock avoidance( same locking order)'
mv 'top questions in mind.html' '2016-11-11-top questions in mind.html'
mv 'top questions in mind.resources' '2016-11-11-top questions in mind'
mv 'tvOS:.html' '2016-11-05-tvOS:.html'
mv 'tvOS:.resources' '2016-11-05-tvOS:'
mv 'Twitter OAuth: 3-legged authorization (by example).html' '2015-10-27-Twitter OAuth: 3-legged authorization (by example).html'
mv 'Twitter OAuth: 3-legged authorization (by example).resources' '2015-10-27-Twitter OAuth: 3-legged authorization (by example)'
mv 'Two steps to dual boot Ubuntu w/ windows.html' '2012-11-04-Two steps to dual boot Ubuntu w/ windows.html'
mv 'Two steps to dual boot Ubuntu w/ windows.resources' '2012-11-04-Two steps to dual boot Ubuntu w/ windows'
mv 'Types of React components.html' '2017-11-09-Types of React components.html'
mv 'Types of React components.resources' '2017-11-09-Types of React components'
mv 'ubuntu 14.04 work environment setup.html' '2014-07-22-ubuntu 14.04 work environment setup.html'
mv 'ubuntu 14.04 work environment setup.resources' '2014-07-22-ubuntu 14.04 work environment setup'
mv 'UI State.html' '2014-08-08-UI State.html'
mv 'UI State.resources' '2014-08-08-UI State'
mv 'understand Rubymine diff colors.html' '2016-11-15-understand Rubymine diff colors.html'
mv 'understand Rubymine diff colors.resources' '2016-11-15-understand Rubymine diff colors'
mv 'Unix is not a kernel.html' '2013-12-20-Unix is not a kernel.html'
mv 'Unix is not a kernel.resources' '2013-12-20-Unix is not a kernel'
mv 'Unix program execution.html' '2013-12-20-Unix program execution.html'
mv 'Unix program execution.resources' '2013-12-20-Unix program execution'
mv 'Unix system calls.html' '2013-12-17-Unix system calls.html'
mv 'Unix system calls.resources' '2013-12-17-Unix system calls'
mv 'Use qmake comes with the qt package to generate Makefile..html' '2013-03-08-Use qmake comes with the qt package to generate Makefile..html'
mv 'Use qmake comes with the qt package to generate Makefile..resources' '2013-03-08-Use qmake comes with the qt package to generate Makefile.'
mv 'View object lifecycle : iOS vs HTML.html' '2016-11-05-View object lifecycle : iOS vs HTML.html'
mv 'View object lifecycle : iOS vs HTML.resources' '2016-11-05-View object lifecycle : iOS vs HTML'
mv 'Vim的ex命令.html' '2012-08-12-Vim的ex命令.html'
mv 'Vim的ex命令.resources' '2012-08-12-Vim的ex命令'
mv 'virtualbox linux guest file sharing sample code.html' '2012-09-11-virtualbox linux guest file sharing sample code.html'
mv 'virtualbox linux guest file sharing sample code.resources' '2012-09-11-virtualbox linux guest file sharing sample code'
mv 'Visual comparison of three types of networks: Telephone network and Television network and Computer network.html' '2013-09-24-Visual comparison of three types of networks: Telephone network and Television network and Computer network.html'
mv 'Visual comparison of three types of networks: Telephone network and Television network and Computer network.resources' '2013-09-24-Visual comparison of three types of networks: Telephone network and Television network and Computer network'
mv 'Ways to connect a database.html' '2012-08-23-Ways to connect a database.html'
mv 'Ways to connect a database.resources' '2012-08-23-Ways to connect a database'
mv 'Web Service API Authentication.html' '2015-10-13-Web Service API Authentication.html'
mv 'Web Service API Authentication.resources' '2015-10-13-Web Service API Authentication'
mv 'webpack url-loader.html' '2017-01-06-webpack url-loader.html'
mv 'webpack url-loader.resources' '2017-01-06-webpack url-loader'
mv 'What "meta" means?.html' '2013-11-12-What "meta" means?.html'
mv 'What "meta" means?.resources' '2013-11-12-What "meta" means?'
mv 'what are sign up and sign in for.html' '2013-04-25-what are sign up and sign in for.html'
mv 'what are sign up and sign in for.resources' '2013-04-25-what are sign up and sign in for'
mv 'What does a member and collection route mean?.html' '2013-04-25-What does a member and collection route mean?.html'
mv 'What does a member and collection route mean?.resources' '2013-04-25-What does a member and collection route mean?'
mv 'What does controlled component mean.html' '2017-11-09-What does controlled component mean.html'
mv 'What does controlled component mean.resources' '2017-11-09-What does controlled component mean'
mv 'What does send() do in Ruby?.html' '2015-05-27-What does send() do in Ruby?.html'
mv 'What does send() do in Ruby?.resources' '2015-05-27-What does send() do in Ruby?'
mv 'What I've learned in schools.html' '2013-11-23-What I've learned in schools.html'
mv 'What I've learned in schools.resources' '2013-11-23-What I've learned in schools'
mv 'What is a promise and what is then method?.html' '2013-11-13-What is a promise and what is then method?.html'
mv 'What is a promise and what is then method?.resources' '2013-11-13-What is a promise and what is then method?'
mv 'what is swap and disk cache?.html' '2013-11-12-what is swap and disk cache?.html'
mv 'what is swap and disk cache?.resources' '2013-11-12-what is swap and disk cache?'
mv 'What is view and view controller?.html' '2013-08-30-What is view and view controller?.html'
mv 'What is view and view controller?.resources' '2013-08-30-What is view and view controller?'
mv 'What is viewport?.html' '2013-10-19-What is viewport?.html'
mv 'What is viewport?.resources' '2013-10-19-What is viewport?'
mv 'What's a conflict in Version Control System?.html' '2013-10-24-What's a conflict in Version Control System?.html'
mv 'What's a conflict in Version Control System?.resources' '2013-10-24-What's a conflict in Version Control System?'
mv 'What's network.html' '2012-11-07-What's network.html'
mv 'What's network.resources' '2012-11-07-What's network'
mv 'What's new in Angular 2.0.html' '2014-12-05-What's new in Angular 2.0.html'
mv 'What's new in Angular 2.0.resources' '2014-12-05-What's new in Angular 2.0'
mv 'What’s IntelliSort.html' '2015-08-17-What’s IntelliSort.html'
mv 'What’s IntelliSort.resources' '2015-08-17-What’s IntelliSort'
mv 'What’s the difference between angular-material and polymer.html' '2014-12-06-What’s the difference between angular-material and polymer.html'
mv 'What’s the difference between angular-material and polymer.resources' '2014-12-06-What’s the difference between angular-material and polymer'
mv 'when to git rebase?.html' '2014-12-04-when to git rebase?.html'
mv 'when to git rebase?.resources' '2014-12-04-when to git rebase?'
mv 'where to store data?.html' '2013-09-10-where to store data?.html'
mv 'where to store data?.resources' '2013-09-10-where to store data?'
mv 'Whose-Our-Boss solution.html' '2016-03-22-Whose-Our-Boss solution.html'
mv 'Whose-Our-Boss solution.resources' '2016-03-22-Whose-Our-Boss solution'
mv 'Why Associations?.html' '2013-04-28-Why Associations?.html'
mv 'Why Associations?.resources' '2013-04-28-Why Associations?'
mv 'Why to use BDM or JTAG.html' '2012-10-20-Why to use BDM or JTAG.html'
mv 'Why to use BDM or JTAG.resources' '2012-10-20-Why to use BDM or JTAG'
mv 'Why use Google Calendar API like syntax not working for our Timeline project?.html' '2013-10-09-Why use Google Calendar API like syntax not working for our Timeline project?.html'
mv 'Why use Google Calendar API like syntax not working for our Timeline project?.resources' '2013-10-09-Why use Google Calendar API like syntax not working for our Timeline project?'
mv 'work with ActiveRecord associations in Elasticsearch.html' '2014-09-25-work with ActiveRecord associations in Elasticsearch.html'
mv 'work with ActiveRecord associations in Elasticsearch.resources' '2014-09-25-work with ActiveRecord associations in Elasticsearch'
mv '《Linux高性能服务器编程》讲解的是实现高性能服务端软件所使用的技术（TCP/IP, I/O复用，多进程，多线程）；而《构建高性能web站点》讲的是如何使用那.html' '2014-07-16-《Linux高性能服务器编程》讲解的是实现高性能服务端软件所使用的技术（TCP/IP, I/O复用，多进程，多线程）；而《构建高性能web站点》讲的是如何使用那.html'
mv '《Linux高性能服务器编程》讲解的是实现高性能服务端软件所使用的技术（TCP/IP, I/O复用，多进程，多线程）；而《构建高性能web站点》讲的是如何使用那.resources' '2014-07-16-《Linux高性能服务器编程》讲解的是实现高性能服务端软件所使用的技术（TCP/IP, I/O复用，多进程，多线程）；而《构建高性能web站点》讲的是如何使用那'
mv '《人月神话》读后感.html' '2015-10-06-《人月神话》读后感.html'
mv '《人月神话》读后感.resources' '2015-10-06-《人月神话》读后感'
mv '《什么是数学》学习笔记.html' '2012-02-11-《什么是数学》学习笔记.html'
mv '《什么是数学》学习笔记.resources' '2012-02-11-《什么是数学》学习笔记'
mv '《算法导论》学习笔记.html' '2012-11-25-《算法导论》学习笔记.html'
mv '《算法导论》学习笔记.resources' '2012-11-25-《算法导论》学习笔记'
mv '《软件设计师》笔记.html' '2012-10-22-《软件设计师》笔记.html'
mv '《软件设计师》笔记.resources' '2012-10-22-《软件设计师》笔记'
mv '一些产品的思考.html' '2017-10-23-一些产品的思考.html'
mv '一些产品的思考.resources' '2017-10-23-一些产品的思考'
mv '为什么 APP 要用 token 而不用 session 认证？.html' '2015-10-14-为什么 APP 要用 token 而不用 session 认证？.html'
mv '为什么 APP 要用 token 而不用 session 认证？.resources' '2015-10-14-为什么 APP 要用 token 而不用 session 认证？'
mv '主流原型工具比较.html' '2017-06-13-主流原型工具比较.html'
mv '主流原型工具比较.resources' '2017-06-13-主流原型工具比较'
mv '做什么软件都一样.html' '2014-10-29-做什么软件都一样.html'
mv '做什么软件都一样.resources' '2014-10-29-做什么软件都一样'
mv '单纯只是看代码的话，应该不需要借助别人书籍的帮助吧，自己看就好了.html' '2017-01-14-单纯只是看代码的话，应该不需要借助别人书籍的帮助吧，自己看就好了.html'
mv '单纯只是看代码的话，应该不需要借助别人书籍的帮助吧，自己看就好了.resources' '2017-01-14-单纯只是看代码的话，应该不需要借助别人书籍的帮助吧，自己看就好了'
mv '向量空间.html' '2011-12-11-向量空间.html'
mv '向量空间.resources' '2011-12-11-向量空间'
mv '如何使用云梯智能加速，且不影响公司内网的访问.html' '2015-11-11-如何使用云梯智能加速，且不影响公司内网的访问.html'
mv '如何使用云梯智能加速，且不影响公司内网的访问.resources' '2015-11-11-如何使用云梯智能加速，且不影响公司内网的访问'
mv '如何双面打印.html' '2015-04-08-如何双面打印.html'
mv '如何双面打印.resources' '2015-04-08-如何双面打印'
mv '如何科学研究？.html' '2016-01-11-如何科学研究？.html'
mv '如何科学研究？.resources' '2016-01-11-如何科学研究？'
mv '如何销毁 javascript 对象.html' '2013-10-20-如何销毁 javascript 对象.html'
mv '如何销毁 javascript 对象.resources' '2013-10-20-如何销毁 javascript 对象'
mv '对 scanf 函数的新认识的更正：其实什么也没发现.html' '2011-12-15-对 scanf 函数的新认识的更正：其实什么也没发现.html'
mv '对 scanf 函数的新认识的更正：其实什么也没发现.resources' '2011-12-15-对 scanf 函数的新认识的更正：其实什么也没发现'
mv '小窍门： 如何在Keynote中插入代码且不丢失样式？.html' '2014-12-12-小窍门： 如何在Keynote中插入代码且不丢失样式？.html'
mv '小窍门： 如何在Keynote中插入代码且不丢失样式？.resources' '2014-12-12-小窍门： 如何在Keynote中插入代码且不丢失样式？'
mv '尺规作图与数域.html' '2011-08-30-尺规作图与数域.html'
mv '尺规作图与数域.resources' '2011-08-30-尺规作图与数域'
mv '快排的核心：分区子程序.html' '2011-08-29-快排的核心：分区子程序.html'
mv '快排的核心：分区子程序.resources' '2011-08-29-快排的核心：分区子程序'
mv '我喜欢玩的游戏类型.html' '2016-11-23-我喜欢玩的游戏类型.html'
mv '我喜欢玩的游戏类型.resources' '2016-11-23-我喜欢玩的游戏类型'
mv '我喜欢看什么类型的电影？.html' '2017-06-18-我喜欢看什么类型的电影？.html'
mv '我喜欢看什么类型的电影？.resources' '2017-06-18-我喜欢看什么类型的电影？'
mv '我想看什么样的新闻？.html' '2017-06-18-我想看什么样的新闻？.html'
mv '我想看什么样的新闻？.resources' '2017-06-18-我想看什么样的新闻？'
mv '整数的表示.html' '2013-08-04-整数的表示.html'
mv '整数的表示.resources' '2013-08-04-整数的表示'
mv '文明的车让人.html' '2016-04-10-文明的车让人.html'
mv '文明的车让人.resources' '2016-04-10-文明的车让人'
mv '无标题笔记.html' '2015-05-08-无标题笔记.html'
mv '无标题笔记.resources' '2015-05-08-无标题笔记'
mv '本质上困难的.html' '2014-06-09-本质上困难的.html'
mv '本质上困难的.resources' '2014-06-09-本质上困难的'
mv '极限^数学.html' '2011-12-13-极限^数学.html'
mv '极限^数学.resources' '2011-12-13-极限^数学'
mv '构建嵌入式Linux系统.html' '2012-10-30-构建嵌入式Linux系统.html'
mv '构建嵌入式Linux系统.resources' '2012-10-30-构建嵌入式Linux系统'
mv '武汉的文明.html' '2016-04-10-武汉的文明.html'
mv '武汉的文明.resources' '2016-04-10-武汉的文明'
mv '汽车的外观和手机的外观对使用者的差别.html' '2017-10-25-汽车的外观和手机的外观对使用者的差别.html'
mv '汽车的外观和手机的外观对使用者的差别.resources' '2017-10-25-汽车的外观和手机的外观对使用者的差别'
mv '汽车运动力学.html' '2017-08-31-汽车运动力学.html'
mv '汽车运动力学.resources' '2017-08-31-汽车运动力学'
mv '炉石传说：一场奇迹般的胜利.html' '2016-04-09-炉石传说：一场奇迹般的胜利.html'
mv '炉石传说：一场奇迹般的胜利.resources' '2016-04-09-炉石传说：一场奇迹般的胜利'
mv '点子：把校企合作的经历作为session分享.html' '2017-02-17-点子：把校企合作的经历作为session分享.html'
mv '点子：把校企合作的经历作为session分享.resources' '2017-02-17-点子：把校企合作的经历作为session分享'
mv '猎头打电话来，我好言好语跟他说话，一听到我不合适，就直接挂我电话。非常没礼貌。.html' '2017-11-15-猎头打电话来，我好言好语跟他说话，一听到我不合适，就直接挂我电话。非常没礼貌。.html'
mv '猎头打电话来，我好言好语跟他说话，一听到我不合适，就直接挂我电话。非常没礼貌。.resources' '2017-11-15-猎头打电话来，我好言好语跟他说话，一听到我不合适，就直接挂我电话。非常没礼貌。'
mv '生活小记：累与梦.html' '2016-04-10-生活小记：累与梦.html'
mv '生活小记：累与梦.resources' '2016-04-10-生活小记：累与梦'
mv '用简单计算器计算e的值.html' '2010-10-10-用简单计算器计算e的值.html'
mv '用简单计算器计算e的值.resources' '2010-10-10-用简单计算器计算e的值'
mv '短除法.html' '2011-09-01-短除法.html'
mv '短除法.resources' '2011-09-01-短除法'
mv '编程珠玑 第一章.html' '2012-02-11-编程珠玑 第一章.html'
mv '编程珠玑 第一章.resources' '2012-02-11-编程珠玑 第一章'
mv '编程珠玑（续）tags.html' '2012-11-09-编程珠玑（续）tags.html'
mv '编程珠玑（续）tags.resources' '2012-11-09-编程珠玑（续）tags'
mv '编程的原则：做单件事并做好。.html' '2011-12-11-编程的原则：做单件事并做好。.html'
mv '编程的原则：做单件事并做好。.resources' '2011-12-11-编程的原则：做单件事并做好。'
mv '网化商城国内竞品分析.html' '2016-05-13-网化商城国内竞品分析.html'
mv '网化商城国内竞品分析.resources' '2016-05-13-网化商城国内竞品分析'
mv '虚函数和接口.html' '2012-08-18-虚函数和接口.html'
mv '虚函数和接口.resources' '2012-08-18-虚函数和接口'
mv '计算机体系结构.html' '2012-10-24-计算机体系结构.html'
mv '计算机体系结构.resources' '2012-10-24-计算机体系结构'
mv '论人际交往.html' '2014-04-27-论人际交往.html'
mv '论人际交往.resources' '2014-04-27-论人际交往'
mv '面对不同的人有不同的表达方式.html' '2017-02-28-面对不同的人有不同的表达方式.html'
mv '面对不同的人有不同的表达方式.resources' '2017-02-28-面对不同的人有不同的表达方式'
